export {default as Header} from './Header';
export {default as Footer} from './Footer';
export {default as CryptoDetails} from './CryptoDetails';
export {default as Cryptocurrencies} from './Cryptocurrencies';
export {default as Exchanges} from './Exchanges';
export {default as Homepage} from './Homepage';
export {default as News} from './News';
export {default as Cryptocard} from './Cryptocard';
export {default as Loader} from './Loader';
export {default as LineChart} from './LineChart'
export {default as Feedback} from './Feedback';
export {default as Contact} from './Contact';
export {default as About} from './About';
export {default as Login} from './Login';
export {default as MainView} from './MainView';
export {default as Register} from './Register';